In [ ]:
1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?


In [8]:
#1.	Write a Python Program to Add Two Matrices?
import numpy as np
x=np.array([[1,2,5],[3,4,9]])
y=np.array([[5,6,3],[7,8,12]])
print(x)
print(y)
print("The addition of two matrices",x+y)

print("The addition of two matrices",np.add(x,y))


[[1 2 5]
 [3 4 9]]
[[ 5  6  3]
 [ 7  8 12]]
The addition of two matrices [[ 6  8  8]
 [10 12 21]]
The addition of two matrices [[ 6  8  8]
 [10 12 21]]


In [14]:
#Solution 2:
#1.	Write a Python Program to Add Two Matrices?
A = [[1,3,4],
    [ 5,6,4],
    [8 ,7,1]]

B = [[9,8,4],
    [1,7,5],
    [3,5,6]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]


for i in range(len(A)):
   for j in range(len(A[0])):
       result[i][j] = A[i][j] + B[i][j]

for r in result:
   print(r)

[10, 11, 8]
[6, 13, 9]
[11, 12, 7]


In [11]:
#2.	Write a Python Program to Multiply Two Matrices?
import numpy as np
x=np.array([[1,2,9],[3,4,6],[7,8,9]])
y=np.array([[5,6,9],[7,8,6],[6,9,3]])
print(x)
print(y)
print("The Multiplication of two matrices",x.dot(y)) #matrix multiplication
print("The Multiplication of two matrices",x*y) #element wise multiplication
print("The Multiplication of two matrices",np.multiply(x,y)) #element wise multiplication



[[1 2 9]
 [3 4 6]
 [7 8 9]]
[[5 6 9]
 [7 8 6]
 [6 9 3]]
The Multiplication of two matrices [[ 73 103  48]
 [ 79 104  69]
 [145 187 138]]
The Multiplication of two matrices [[ 5 12 81]
 [21 32 36]
 [42 72 27]]
The Multiplication of two matrices [[ 5 12 81]
 [21 32 36]
 [42 72 27]]


In [ ]:
#Solution2:
